name: windmillcode_peerdart
version: 1.5.4030
homepage: https://github.com/WindMillCode/peerdart
description: Simple peer-to-peer with WebRTC for Dart. PeerJS port for Flutter.
repository: https://github.com/WindMillCode/peerdart
topics:
  - webrtc
  - file-transfer
  - flutter
  - datachannel
  - peer

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.22.0"
dependencies:
  http: ^1.2.2
  uuid: ^4.5.1
  flutter_webrtc: ^0.12.0
  socket_io_client: ^3.0.0
  events_emitter: ^0.5.2
  sdp_transform: ^0.3.2
  msgpack_dart: ^1.0.1
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0
dev_dependencies:
  lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  unused_import_remover: ^1.0.1
