name: peerdart
version: 1.5.4000
homepage: https://github.com/MuhammedKpln/peerdart
description: Simple peer-to-peer with WebRTC for Dart. PeerJS port for Flutter.
repository: https://github.com/MuhammedKpln/peerdart
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.22.0"
dependencies:
  http: ^1.1.0
  uuid: ^4.1.0
  flutter_webrtc: ^0.9.45
  web_socket_channel: ^3.0.0
  events_emitter: ^0.5.2
  sdp_transform: ^0.3.2
  pubspec: ^2.3.0
  msgpack_dart: ^1.0.1
dev_dependencies:
  lints: ^2.1.1
  flutter_test:
    sdk: flutter
